"""Tests for the AGENTS.md / tota.skill.json generator."""
from __future__ import annotations

import json
from pathlib import Path

import pytest

import generate_agents as ga


SKILL_DIR = Path(__file__).resolve().parent.parent.parent


# ---------------------------------------------------------------------------
# parse_frontmatter
# ---------------------------------------------------------------------------


def test_parse_frontmatter_on_live_skill():
    fm = ga.parse_frontmatter(SKILL_DIR / "SKILL.md")
    assert fm.name == "x-virality"
    assert "X" in fm.description or "x" in fm.description.lower()
    assert len(fm.description) > 50  # description is substantive


def test_parse_frontmatter_missing_raises(tmp_path: Path):
    md = tmp_path / "no-frontmatter.md"
    md.write_text("# Just a heading\n")
    with pytest.raises(RuntimeError, match="No YAML frontmatter"):
        ga.parse_frontmatter(md)


def test_parse_frontmatter_missing_name_raises(tmp_path: Path):
    md = tmp_path / "no-name.md"
    md.write_text("---\ndescription: foo\n---\n")
    with pytest.raises(RuntimeError, match="No `name:`"):
        ga.parse_frontmatter(md)


def test_parse_frontmatter_missing_description_raises(tmp_path: Path):
    md = tmp_path / "no-desc.md"
    md.write_text("---\nname: x\n---\n")
    with pytest.raises(RuntimeError, match="No `description:`"):
        ga.parse_frontmatter(md)


def test_parse_frontmatter_collapses_whitespace(tmp_path: Path):
    md = tmp_path / "multiline.md"
    md.write_text(
        "---\n"
        "name: skill\n"
        "description: First line\n"
        "  second line\n"
        "  third line.\n"
        "---\n"
        "body\n"
    )
    fm = ga.parse_frontmatter(md)
    assert fm.description == "First line second line third line."


# ---------------------------------------------------------------------------
# list_skill_files
# ---------------------------------------------------------------------------


def test_list_skill_files_excludes_tests():
    files = ga.list_skill_files(SKILL_DIR)
    for f in files:
        assert "/tests/" not in str(f), f"tests/ should be excluded: {f}"


def test_list_skill_files_includes_skill_md():
    files = ga.list_skill_files(SKILL_DIR)
    names = {f.name for f in files}
    assert "SKILL.md" in names


def test_list_skill_files_includes_recipes():
    files = ga.list_skill_files(SKILL_DIR)
    rel_strs = {str(f.relative_to(SKILL_DIR)) for f in files}
    # at least the reply-bait recipe ships
    assert any("recipes/reply-bait.md" in s for s in rel_strs)


# ---------------------------------------------------------------------------
# render_agents_md
# ---------------------------------------------------------------------------


def test_render_agents_md_includes_description():
    fm = ga.Frontmatter(name="x-virality", description="The cool skill.")
    md = ga.render_agents_md(fm, ["a.md", "b.md"])
    assert "The cool skill." in md
    assert "a.md" in md
    assert "b.md" in md
    assert "SKILL.md" in md


def test_render_agents_md_has_generated_marker():
    md = ga.render_agents_md(ga.Frontmatter("x", "d"), [])
    assert "Generated by" in md or "generated" in md.lower()


# ---------------------------------------------------------------------------
# render_tota_skill_json
# ---------------------------------------------------------------------------


def test_tota_skill_json_is_valid_json():
    text = ga.render_tota_skill_json(ga.Frontmatter("n", "d"), ["a.md"])
    data = json.loads(text)
    assert data["name"] == "n"
    assert data["description"] == "d"
    assert "entrypoint" in data
    assert "references" in data
    assert "tools" in data
    assert "schema_version" in data


def test_tota_skill_json_lists_tools():
    text = ga.render_tota_skill_json(ga.Frontmatter("n", "d"), [])
    data = json.loads(text)
    tool_strs = data["tools"]
    assert any("score_simulator.py" in t for t in tool_strs)
    assert any("verify_refs.py" in t for t in tool_strs)


# ---------------------------------------------------------------------------
# generate() integration
# ---------------------------------------------------------------------------


def test_generate_returns_two_artifacts():
    artifacts = ga.generate()
    paths = [p.name for p in artifacts]
    assert "AGENTS.md" in paths
    assert "tota.skill.json" in paths


def test_generated_tota_json_parses():
    artifacts = ga.generate()
    tota_path = next(p for p in artifacts if p.name == "tota.skill.json")
    data = json.loads(artifacts[tota_path])
    assert data["name"] == "x-virality"
    assert len(data["references"]) > 0


# ---------------------------------------------------------------------------
# main() --check mode
# ---------------------------------------------------------------------------


def test_main_check_after_write_is_clean(tmp_path: Path, monkeypatch, capsys):
    """Write artifacts, then --check should pass."""
    # Run main without --check to write.
    rc_write = ga.main([])
    assert rc_write == 0
    # Now --check should be clean.
    rc_check = ga.main(["--check"])
    assert rc_check == 0
    out = capsys.readouterr().out
    assert "OK" in out or "in sync" in out
