#!/usr/bin/env python3
"""Generate agent-specific install artifacts for the x-virality skill.

Two outputs:
  - AGENTS.md (repo root) — Codex-style instructions pointing at SKILL.md
    and the reference files. Codex agents read AGENTS.md on session start.
  - tota.skill.json (repo root) — A generic JSON skill manifest that other
    agents (Tota Agent or any agent reading a JSON schema) can ingest.

Both files are generated from SKILL.md's YAML frontmatter (name, description)
plus the on-disk file inventory inside `.claude/skills/x-virality/`.

Usage:
    python .claude/skills/x-virality/tools/generate_agents.py
    python .claude/skills/x-virality/tools/generate_agents.py --check  # CI mode

`--check` exits non-zero if the on-disk artifacts differ from what would be
generated. Use this in CI to ensure the artifacts stay in sync with SKILL.md.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT_MARKER = ".git"


def find_repo_root(start: Path) -> Path:
    current = start.resolve()
    while current != current.parent:
        if (current / REPO_ROOT_MARKER).exists():
            return current
        current = current.parent
    raise RuntimeError(f"Could not find repo root from {start}")


@dataclass(frozen=True)
class Frontmatter:
    name: str
    description: str


FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)
NAME_RE = re.compile(r"^name:\s*(.+?)\s*$", re.MULTILINE)
DESCRIPTION_RE = re.compile(r"^description:\s*(.+?)\n(?:[a-z_-]+:|---)",
                            re.DOTALL | re.MULTILINE)


def parse_frontmatter(skill_md: Path) -> Frontmatter:
    """Extract name + description from SKILL.md's YAML frontmatter.

    We use simple regexes (no YAML dep). The description is everything from
    `description:` up to the next top-level key or the closing `---`.
    """
    text = skill_md.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise RuntimeError(f"No YAML frontmatter found in {skill_md}")
    block = match.group(1)
    name_match = NAME_RE.search(block)
    if not name_match:
        raise RuntimeError(f"No `name:` field in frontmatter of {skill_md}")
    description_match = DESCRIPTION_RE.search(block + "\n---")
    if not description_match:
        raise RuntimeError(
            f"No `description:` field in frontmatter of {skill_md}"
        )
    description = " ".join(description_match.group(1).split())
    return Frontmatter(name=name_match.group(1), description=description)


def list_skill_files(skill_dir: Path) -> list[Path]:
    """Every markdown reference the agent should know about."""
    return sorted(
        p for p in skill_dir.rglob("*.md")
        if "/tests/" not in str(p)
    )


def relative_paths(files: list[Path], root: Path) -> list[str]:
    return sorted(str(p.relative_to(root)) for p in files)


def render_agents_md(fm: Frontmatter, refs: list[str]) -> str:
    """Generate AGENTS.md text from the skill's frontmatter + file list."""
    ref_block = "\n".join(f"  - {p}" for p in refs)
    return (
        "# AGENTS.md\n\n"
        "## x-virality skill\n\n"
        f"**Description:** {fm.description}\n\n"
        "When the user's request matches the description above, follow the "
        "skill at `.claude/skills/x-virality/SKILL.md`. Read referenced files "
        "on demand:\n\n"
        f"{ref_block}\n\n"
        "## How to use\n\n"
        "1. Load `.claude/skills/x-virality/SKILL.md` first.\n"
        "2. For any specific question (signals, recipes, video, risk, "
        "distribution), open the referenced file.\n"
        "3. Before reporting a draft as ready, walk `.claude/skills/"
        "x-virality/checklist.md`.\n"
        "4. (Optional) Run "
        "`python .claude/skills/x-virality/tools/score_simulator.py` to sanity-"
        "check predicted signal weights.\n\n"
        "## Roadmap\n\n"
        "See `.claude/skills/x-virality/ROADMAP.md`. GitHub Issues mirror "
        "is pending — until then ROADMAP.md is the canonical sprint tracker.\n\n"
        "<!-- Generated by .claude/skills/x-virality/tools/generate_agents.py -->\n"
    )


def render_tota_skill_json(fm: Frontmatter, refs: list[str]) -> str:
    """Generate a generic JSON skill manifest."""
    return json.dumps(
        {
            "name": fm.name,
            "description": fm.description,
            "entrypoint": ".claude/skills/x-virality/SKILL.md",
            "references": refs,
            "tools": [
                ".claude/skills/x-virality/tools/score_simulator.py",
                ".claude/skills/x-virality/tools/verify_refs.py",
                ".claude/skills/x-virality/tools/checklist_cli.py",
                ".claude/skills/x-virality/tools/measurement_loop.py",
            ],
            "checklist": ".claude/skills/x-virality/checklist.md",
            "roadmap": ".claude/skills/x-virality/ROADMAP.md",
            "schema_version": 1,
        },
        indent=2,
    ) + "\n"


def generate(skill_dir: Path = SKILL_DIR) -> dict[Path, str]:
    """Compute the desired contents of each generated artifact."""
    root = find_repo_root(skill_dir)
    fm = parse_frontmatter(skill_dir / "SKILL.md")
    files = list_skill_files(skill_dir)
    refs = relative_paths(files, root)

    return {
        root / "AGENTS.md": render_agents_md(fm, refs),
        root / "tota.skill.json": render_tota_skill_json(fm, refs),
    }


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Generate AGENTS.md and tota.skill.json from SKILL.md."
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Exit non-zero if on-disk artifacts differ from generated.",
    )
    args = parser.parse_args(argv)

    artifacts = generate()
    drift: list[tuple[Path, str, str]] = []
    for path, expected in artifacts.items():
        if path.exists():
            actual = path.read_text(encoding="utf-8")
        else:
            actual = ""
        if actual != expected:
            drift.append((path, actual, expected))

    if args.check:
        if drift:
            print(
                f"generate_agents: {len(drift)} file(s) out of sync.\n"
                "Run without --check to regenerate."
            )
            for path, _actual, _expected in drift:
                print(f"  drift: {path}")
            return 1
        print("generate_agents: OK (artifacts in sync)")
        return 0

    for path, _actual, expected in drift:
        path.write_text(expected, encoding="utf-8")
        print(f"generate_agents: wrote {path}")

    if not drift:
        print("generate_agents: no changes")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
